import type { HistoryEvent, IssueRevisions, ServerIssue } from './types'

const commonHistory = (title: string): HistoryEvent[] => [
  { at: '09-22 10:35', actor: '李予 / 审核员', action: '创建问题', detail: `录入 ${title}，并关联页面录屏。` },
  { at: '09-24 16:10', actor: '系统', action: '根因聚类', detail: '与同类问题合并，保留子问题追溯关系。' },
]

/** 字段级版本号：谁、在什么时候把该字段改成当前版本 */
const rev = (revNo: number, actor: string, at: string): IssueRevisions => ({
  status: { rev: revNo, actor, at },
  rootCause: { rev: 1, actor: '李予 / 审核员', at: '09-22 10:35' },
  fixNote: { rev: 1, actor: '系统', at: '09-24 16:10' },
  retestEnv: { rev: 1, actor: '系统', at: '09-24 16:10' },
  retestEvidence: { rev: 1, actor: '系统', at: '09-24 16:10' },
  retestNote: { rev: 1, actor: '系统', at: '09-24 16:10' },
})

const withRevision = (
  issue: Omit<ServerIssue, 'revision'>,
  revision: IssueRevisions,
): ServerIssue => ({ ...issue, revision })

export const seedIssues: ServerIssue[] = [
  withRevision(
    {
      key: 'A11Y-1048',
      title: '商品筛选抽屉无法通过键盘关闭',
      site: '商城 Web',
      version: 'v4.18',
      wcag: ['2.1.2 无键盘陷阱', '2.1.1 键盘'],
      issueType: '键盘操作',
      impact: '致命',
      affected: '筛选面板 / 移动端与桌面键盘用户',
      reproduction: '打开商品筛选抽屉，使用 Tab 遍历后按 Esc，焦点仍循环在抽屉内部。',
      evidence: 'https://evidence.example.com/a11y-1048',
      rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
      status: '待复测',
      priority: 'P0',
      team: '前端基础组件组',
      owner: '何沐',
      dueDate: '2026-10-06',
      mergedKeys: ['A11Y-1052', 'A11Y-1061'],
      fixNote: '补充 Esc 关闭与 focus trap 退出逻辑，并在关闭后把焦点归还触发按钮。',
      retestEnv: 'Chrome 140 / 商城 Web v4.18.3',
      retestRecords: [],
      history: [
        ...commonHistory('筛选抽屉键盘陷阱'),
        { at: '10-04 18:22', actor: '何沐 / 前端基础组件组', action: '提交修复', detail: '补充 Esc 关闭、焦点归还逻辑，提交复测。' },
      ],
    },
    {
      ...rev(3, '何沐 / 前端基础组件组', '10-04 18:22'),
      fixNote: { rev: 2, actor: '何沐 / 前端基础组件组', at: '10-04 18:22' },
      retestEnv: { rev: 2, actor: '何沐 / 前端基础组件组', at: '10-04 18:22' },
    },
  ),
  withRevision(
    {
      key: 'A11Y-1052',
      title: '客服弹窗焦点无法返回触发按钮',
      site: '商城 Web',
      version: 'v4.18',
      wcag: ['2.4.3 焦点顺序'],
      issueType: '焦点管理',
      impact: '严重',
      affected: '客服入口 / 所有键盘用户',
      reproduction: '打开客服弹窗，关闭后焦点落到 body。',
      evidence: 'https://evidence.example.com/a11y-1052',
      rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
      status: '已通过',
      priority: 'P1',
      team: '前端基础组件组',
      owner: '何沐',
      dueDate: '2026-10-03',
      mergedKeys: [],
      fixNote: '增加关闭后的 triggerRef.focus 恢复逻辑。',
      retestEnv: 'Chrome 140 / VoiceOver / 商城 v4.18.3',
      retestEvidence: '本机录屏 keyboard-focus-return.mp4（已归档）',
      retestRecords: [{ id: 'RT-22', actor: '苏禾', result: '通过', note: '焦点返回触发按钮，顺序正确。', at: '09-28 14:20', environment: 'Chrome 140 / VoiceOver / 商城 v4.18.3', evidence: '本机录屏 keyboard-focus-return.mp4（已归档）' }],
      history: commonHistory('客服弹窗焦点恢复'),
    },
    {
      ...rev(4, '苏禾 / 复测员', '09-28 14:20'),
      fixNote: { rev: 2, actor: '何沐 / 前端基础组件组', at: '09-27 11:02' },
      retestEnv: { rev: 2, actor: '何沐 / 前端基础组件组', at: '09-27 11:02' },
      retestEvidence: { rev: 2, actor: '苏禾 / 复测员', at: '09-28 14:20' },
      retestNote: { rev: 2, actor: '苏禾 / 复测员', at: '09-28 14:20' },
    },
  ),
  withRevision(
    {
      key: 'A11Y-1061',
      title: '优惠券选择层存在键盘循环',
      site: '会员中心',
      version: 'v3.9',
      wcag: ['2.1.2 无键盘陷阱'],
      issueType: '键盘操作',
      impact: '严重',
      affected: '结算券选择 / 键盘用户',
      reproduction: 'Shift+Tab 超过首元素后焦点进入不可见元素。',
      evidence: 'https://evidence.example.com/a11y-1061',
      rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
      status: '待分配',
      priority: 'P1',
      team: '结算体验组',
      owner: '待分配',
      dueDate: '2026-10-10',
      mergedKeys: [],
      retestRecords: [],
      history: commonHistory('优惠券选择层键盘循环'),
    },
    rev(1, '系统', '09-24 16:10'),
  ),
  withRevision(
    {
      key: 'A11Y-1074',
      title: '数据图表颜色对比度不足',
      site: '运营后台',
      version: 'v2.7',
      wcag: ['1.4.11 非文本对比度', '1.4.3 对比度'],
      issueType: '视觉对比',
      impact: '中等',
      affected: '经营趋势图 / 低视力用户',
      reproduction: '趋势线 3 与背景对比度约 2.6:1。',
      evidence: 'https://evidence.example.com/a11y-1074',
      rootCause: '图表主题色板未执行无障碍校验',
      status: '待复测',
      priority: 'P2',
      team: '数据可视化组',
      owner: '赵屿',
      dueDate: '2026-10-09',
      mergedKeys: [],
      fixNote: '更换色板并增加虚线纹理和可切换数据表。',
      retestEnv: 'Safari 26 / 对比度工具 / admin-v2.7.5',
      retestRecords: [],
      history: commonHistory('图表颜色对比度'),
    },
    {
      ...rev(2, '赵屿 / 数据可视化组', '10-03 09:40'),
      fixNote: { rev: 2, actor: '赵屿 / 数据可视化组', at: '10-03 09:40' },
      retestEnv: { rev: 2, actor: '赵屿 / 数据可视化组', at: '10-03 09:40' },
    },
  ),
  withRevision(
    {
      key: 'A11Y-1083',
      title: '表单错误提示未被读屏软件播报',
      site: '采购门户',
      version: 'v1.12',
      wcag: ['3.3.1 错误识别', '4.1.3 状态消息'],
      issueType: '错误提示',
      impact: '严重',
      affected: '供应商注册表单 / 屏幕阅读器用户',
      reproduction: '填写无效税号并提交，视觉提示出现但无 live region。',
      evidence: 'https://evidence.example.com/a11y-1083',
      rootCause: '表单错误组件未接入 aria-live 和字段描述',
      status: '已退回',
      priority: 'P1',
      team: '供应链前端组',
      owner: '顾雪',
      dueDate: '2026-10-05',
      mergedKeys: [],
      fixNote: '计划仅增加视觉错误颜色。',
      retestEnv: 'NVDA 2026.1 / Chrome 140 / portal-v1.12.4',
      retestRecords: [{ id: 'RT-31', actor: '李予', result: '退回', note: '仍需接入 aria-live，并验证字段 aria-describedby。', at: '09-28 11:05', environment: 'NVDA 2026.1 / Chrome 140 / portal-v1.12.2', evidence: '' }],
      history: commonHistory('表单错误提示'),
    },
    {
      ...rev(3, '李予 / 复测员', '09-28 11:05'),
      retestEnv: { rev: 2, actor: '顾雪 / 供应链前端组', at: '09-27 17:30' },
      retestNote: { rev: 2, actor: '李予 / 复测员', at: '09-28 11:05' },
    },
  ),
]
